name: NX Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Ensure correct SHAs for affected commands
        uses: nrwl/nx-set-shas@v4

      - name: Build projects
        run: npx nx run back-end:build --configuration=production

      - name: Archive build artifacts
        run: tar -czf build-output.tar.gz dist

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nx-build-output
          path: build-output.tar.gz

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: nx-build-output

      # Debug: Check if SERVER_URL is set
      - name: Debug Server URL
        run: |
          if [[ -z "$SERVER_URL" ]]; then
            echo "Error: SERVER_URL is not set!"
            exit 1
          else
            echo "Server URL is: $SERVER_URL"
          fi
        env:
          SERVER_URL: ${{ secrets.SERVER_URL }}

      # Debug: Check SSH Connection Before Deployment
      - name: Debug SSH Connection
        run: |
          mkdir -p ~/.ssh
          echo "ssh folder done"
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          echo "ssh private key save id rsa done"
          chmod 600 ~/.ssh/id_rsa
          echo "chmod done"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_URL: ${{ secrets.SERVER_URL }}

      - name: Deploy to server
        run: |
          echo "Transferring build files..."
          scp -o StrictHostKeyChecking=no build-output.tar.gz $SERVER_URL:~/agent-xenon

          echo "Extracting and restarting services..."
          ssh -o StrictHostKeyChecking=no $SERVER_URL "
            cd ~/agent-xenon &&
            tar -xzf build-output.tar.gz &&
            mv ~/agent-xenon/dist/apps/back-end/assets ~/agent-xenon/assets  &&
            mv ~/agent-xenon/dist/apps/back-end/package.json ~/agent-xenon/package.json &&
            mv ~/agent-xenon/dist/apps/back-end/package-lock.json ~/agent-xenon/package-lock.json &&
            mv ~/agent-xenon/dist/apps/back-end/main.js ~/agent-xenon/main.js &&
            pm2 restart 0
          "
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_URL: ${{ secrets.SERVER_URL }}
